[pytest]
addopts = -p no:ddtrace -p no:json-report -p no:metadata
testpaths = tests
norecursedirs = internal_docs dist production_runtime build .git .venv node_modules
asyncio_default_fixture_loop_scope = function
filterwarnings =
    error
